# Generated by Django 5.2.14 on 2026-05-12 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AdminRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('owner_full_name', models.CharField(max_length=180)),
                ('phone', models.CharField(max_length=30)),
                ('city', models.CharField(default='Malabo', max_length=100)),
                ('taxi_count', models.PositiveIntegerField(default=1)),
                ('message', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='admin_requests/documents/')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_admin_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de dueño de taxi',
                'verbose_name_plural': 'Solicitudes de dueños de taxis',
                'ordering': ['-created_at'],
            },
        ),
    ]
