# Generated by Django 5.2.14 on 2026-05-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_admin_approved_adminrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Solicitud KYC de dueño de taxi', 'verbose_name_plural': 'Solicitudes KYC de dueños de taxis'},
        ),
        migrations.RemoveField(
            model_name='adminrequest',
            name='document',
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to='kyc/identity_documents/'),
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='identity_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='main_taxi_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='main_taxi_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='main_taxi_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='main_taxi_plate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='ownership_proof_document',
            field=models.FileField(blank=True, null=True, upload_to='kyc/ownership_proofs/'),
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='selfie_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/selfies/'),
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='taxi_license_document',
            field=models.FileField(blank=True, null=True, upload_to='kyc/taxi_licenses/'),
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='taxi_registration_document',
            field=models.FileField(blank=True, null=True, upload_to='kyc/taxi_documents/'),
        ),
    ]
