# Generated by Django 5.2.14 on 2026-05-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_adminrequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrequest',
            name='activation_fee',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=12),
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='payment_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='kyc/payment_receipts/'),
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminrequest',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
