# Generated by Django 5.2.14 on 2026-05-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_adminrequest_activation_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaaSPaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_fee', models.DecimalField(decimal_places=2, default=50000, max_digits=12)),
                ('primary_bank_name', models.CharField(default='BANGE', max_length=100)),
                ('primary_account_holder', models.CharField(default='TaxiGE Platform', max_length=150)),
                ('primary_account_number', models.CharField(default='100200300400', max_length=100)),
                ('secondary_bank_name', models.CharField(default='ECOBANK', max_length=100)),
                ('secondary_account_holder', models.CharField(default='TaxiGE Platform', max_length=150)),
                ('secondary_account_number', models.CharField(default='Pendiente de configurar', max_length=100)),
                ('payment_instructions', models.TextField(default='Realiza el pago de activación y sube el comprobante. Tu solicitud será revisada por el administrador antes de activar tu cuenta de propietario.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de pago SaaS',
                'verbose_name_plural': 'Configuración de pagos SaaS',
            },
        ),
    ]
