# Generated by Django 5.2.14 on 2026-05-15 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_saaspaymentsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaaSSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=50000, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Activa'), ('expired', 'Expirada'), ('suspended', 'Suspendida'), ('pending', 'Pendiente')], default='active', max_length=20)),
                ('last_payment_reference', models.CharField(blank=True, max_length=120, null=True)),
                ('last_payment_receipt', models.FileField(blank=True, null=True, upload_to='subscriptions/receipts/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saas_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripción SaaS',
                'verbose_name_plural': 'Suscripciones SaaS',
                'ordering': ['-end_date', '-created_at'],
            },
        ),
    ]
