# Generated by Django 5.2.14 on 2026-05-15 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_saassubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaaSPaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=50000, max_digits=12)),
                ('reference', models.CharField(max_length=120)),
                ('receipt', models.FileField(upload_to='subscriptions/payment_history/')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_saas_payments', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='accounts.saassubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saas_payment_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago SaaS',
                'verbose_name_plural': 'Historial de pagos SaaS',
                'ordering': ['-created_at'],
            },
        ),
    ]
