# Generated by Django 5.2.14 on 2026-05-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_saaspaymenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saaspaymentsettings',
            name='secondary_account_holder',
            field=models.CharField(blank=True, default='TaxiGE Platform', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='saaspaymentsettings',
            name='secondary_account_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saaspaymentsettings',
            name='secondary_bank_name',
            field=models.CharField(blank=True, default='ECOBANK', max_length=100, null=True),
        ),
    ]
