# Generated by Django 5.2.14 on 2026-05-12 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='damages/photos/')),
                ('damage_date', models.DateField()),
                ('repaired_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_repair', 'En reparación'), ('repaired', 'Reparado'), ('charged', 'Cobrado al conductor')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='companies.company')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damages', to='drivers.driver')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_damages', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Daño de taxi',
                'verbose_name_plural': 'Daños de taxis',
                'ordering': ['-damage_date', '-created_at'],
            },
        ),
    ]
