# Generated by Django 5.2.14 on 2026-05-12 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('legal_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(default='Malabo', max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('suspended', 'Suspendida'), ('pending', 'Pendiente')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxi_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa de taxi',
                'verbose_name_plural': 'Empresas de taxis',
                'ordering': ['-created_at'],
            },
        ),
    ]
