# Generated by Django 5.2.14 on 2026-05-12 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_code', models.CharField(blank=True, max_length=50, null=True)),
                ('plate_number', models.CharField(max_length=50, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicles/photos/')),
                ('registration_document', models.FileField(blank=True, null=True, upload_to='vehicles/documents/')),
                ('insurance_document', models.FileField(blank=True, null=True, upload_to='vehicles/documents/')),
                ('daily_target_amount', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad que el conductor debe entregar por día', max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('repair', 'En reparación'), ('damaged', 'Dañado'), ('inactive', 'Inactivo')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Taxi',
                'verbose_name_plural': 'Taxis',
                'ordering': ['-created_at'],
            },
        ),
    ]
