# Generated by Django 5.2.14 on 2026-05-13 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiShareInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=120, unique=True)),
                ('role', models.CharField(choices=[('owner', 'Propietario principal'), ('partner', 'Socio'), ('manager', 'Gestor'), ('viewer', 'Solo lectura'), ('accountant', 'Contable')], default='viewer', max_length=20)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_invites', to='companies.company')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_taxi_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitación compartida',
                'verbose_name_plural': 'Invitaciones compartidas',
            },
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Propietario principal'), ('partner', 'Socio'), ('manager', 'Gestor'), ('viewer', 'Solo lectura'), ('accountant', 'Contable')], default='viewer', max_length=20)),
                ('can_view_payments', models.BooleanField(default=True)),
                ('can_view_damages', models.BooleanField(default=True)),
                ('can_add_payments', models.BooleanField(default=False)),
                ('can_add_damages', models.BooleanField(default=False)),
                ('can_edit_data', models.BooleanField(default=False)),
                ('can_invite_members', models.BooleanField(default=False)),
                ('can_export_reports', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miembro de empresa',
                'verbose_name_plural': 'Miembros de empresas',
                'unique_together': {('company', 'user')},
            },
        ),
    ]
